services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=novel_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  proxy-server:
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    ports:
      - "4001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-dummy-key}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-sk-ant-dummy-key}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_KEY=${API_KEY:-your-api-key-for-authentication}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=novel_agent
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - ./proxy-server:/app
      - /app/node_modules
      - /app/dist

volumes:
  redis_data:
  postgres_data:
