# 開発専用 Docker Compose 設定
services:
  # フロントエンド開発サーバー
  frontend-dev:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      target: development
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4001
      - VITE_WS_URL=ws://localhost:4001
      # WSL/esbuild問題の回避
      - ESBUILD_BINARY_PATH=/usr/local/bin/esbuild
    volumes:
      # ソースコードのホットリロード
      - ./apps/frontend:/app/apps/frontend
      - ./packages:/app/packages
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      # node_modulesはコンテナ内で管理
      - frontend_node_modules:/app/apps/frontend/node_modules
      - packages_node_modules:/app/packages/types/node_modules
    working_dir: /app/apps/frontend
    command: ["pnpm", "vite", "--host", "0.0.0.0", "--port", "5173"]
    stdin_open: true
    tty: true

  # バックエンド開発サーバー
  proxy-server-dev:
    build:
      context: .
      dockerfile: ./apps/proxy-server/Dockerfile
      target: base
    ports:
      - "4001:4001"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - PORT=4001
      # AI API Keys (ローカル環境変数から設定)
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - JWT_SECRET=dev-secret-key-only-for-development
    volumes:
      # ソースコードのホットリロード
      - ./apps/proxy-server:/app/apps/proxy-server
      - ./packages:/app/packages
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      # pnpm-lock.yamlの競合を避けるため除外
      # - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      # node_modulesはコンテナ内で管理
      - proxy_node_modules:/app/apps/proxy-server/node_modules
      - packages_node_modules:/app/packages/types/node_modules
    working_dir: /app/apps/proxy-server
    command: ["sh", "-c", "pnpm install && pnpm run dev"]
    stdin_open: true
    tty: true

volumes:
  frontend_node_modules:
  proxy_node_modules:
  packages_node_modules: